<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ProcessSalesOrderPSOIndustryReqABCSImpl.wsdl"/>
      <rootElement name="SiebelMessage" namespace="http://www.sky.com.mx/soasky/ordenes"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../ProcessSalesOrderPSOIndustryReqABCSImpl.wsdl"/>
      <rootElement name="SiebelMessage" namespace="http://www.sky.com.mx/soasky/ordenes"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [FRI NOV 11 13:00:38 CST 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns1="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns0="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns3="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns2="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1"
                xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
                xmlns:orderentryabo="http://www.sky.com.mx/soasky/ordenes"
                xmlns:orderentryabcs="http://xmlns.oracle.com/ABCSImpl/PSOIndustry/Industry//ProcessSalesOrderPSOIndustryReqABCSImpl/V1"
                exclude-result-prefixes="xsi xsl svcdoc plnk soap orderentryabo ns1 ns0 orderentryabcs ns3 xsd corecom ns2 aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <orderentryabo:SiebelMessage>
      <xsl:attribute name="MessageId">
        <xsl:value-of select="/orderentryabo:SiebelMessage/@MessageId"/>
      </xsl:attribute>
      <xsl:attribute name="MessageType">
        <xsl:value-of select="/orderentryabo:SiebelMessage/@MessageType"/>
      </xsl:attribute>
      <xsl:attribute name="IntObjectName">
        <xsl:value-of select="/orderentryabo:SiebelMessage/@IntObjectName"/>
      </xsl:attribute>
      <xsl:attribute name="IntObjectFormat">
        <xsl:value-of select="/orderentryabo:SiebelMessage/@IntObjectFormat"/>
      </xsl:attribute>
      <orderentryabo:ListOfSkyhjComWorkOrder>
        <orderentryabo:ComWorkOrder-Orders>
          <orderentryabo:Id>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:Id"/>
          </orderentryabo:Id>
          <orderentryabo:Account>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:Account"/>
          </orderentryabo:Account>
          <orderentryabo:AccountActionCode>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountActionCode"/>
          </orderentryabo:AccountActionCode>
          <orderentryabo:AccountId>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountId"/>
          </orderentryabo:AccountId>
          <orderentryabo:AccountLoc>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountLoc"/>
          </orderentryabo:AccountLoc>
          <orderentryabo:AccountMarketClass>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountMarketClass"/>
          </orderentryabo:AccountMarketClass>
          <orderentryabo:AccountMarketType>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountMarketType"/>
          </orderentryabo:AccountMarketType>
          <orderentryabo:AccountStatus>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountStatus"/>
          </orderentryabo:AccountStatus>
          <orderentryabo:AccountUpdateFlag>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountUpdateFlag"/>
          </orderentryabo:AccountUpdateFlag>
          <orderentryabo:AccountTechnology>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountTechnology"/>
          </orderentryabo:AccountTechnology>
          <orderentryabo:AccountAntenna>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountAntenna"/>
          </orderentryabo:AccountAntenna>
          <orderentryabo:AccountSatellite>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountSatellite"/>
          </orderentryabo:AccountSatellite>
          <orderentryabo:AgreementId>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AgreementId"/>
          </orderentryabo:AgreementId>
          <orderentryabo:AgreementName>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AgreementName"/>
          </orderentryabo:AgreementName>
          <orderentryabo:BillingProfileBankAccountNumber>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:BillingProfileBankAccountNumber"/>
          </orderentryabo:BillingProfileBankAccountNumber>
          <orderentryabo:BillingProfileBillCycle>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:BillingProfileBillCycle"/>
          </orderentryabo:BillingProfileBillCycle>
          <orderentryabo:BillingProfileClearingHouseCalc>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:BillingProfileClearingHouseCalc"/>
          </orderentryabo:BillingProfileClearingHouseCalc>
          <orderentryabo:BillingProfileClearingHouseId>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:BillingProfileClearingHouseId"/>
          </orderentryabo:BillingProfileClearingHouseId>
          <orderentryabo:BillingProfileCreditCardExpirationDate>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:BillingProfileCreditCardExpirationDate"/>
          </orderentryabo:BillingProfileCreditCardExpirationDate>
          <orderentryabo:BillingProfileCreditCardName>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:BillingProfileCreditCardName"/>
          </orderentryabo:BillingProfileCreditCardName>
          <orderentryabo:BillingProfileCreditCardNumber>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:BillingProfileCreditCardNumber"/>
          </orderentryabo:BillingProfileCreditCardNumber>
          <orderentryabo:BillingProfileCreditCardSecurityCode>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:BillingProfileCreditCardSecurityCode"/>
          </orderentryabo:BillingProfileCreditCardSecurityCode>
          <orderentryabo:BillingProfileId>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:BillingProfileId"/>
          </orderentryabo:BillingProfileId>
          <orderentryabo:BillingProfilePaymentMethod>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:BillingProfilePaymentMethod"/>
          </orderentryabo:BillingProfilePaymentMethod>
          <orderentryabo:CompanyName>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:CompanyName"/>
          </orderentryabo:CompanyName>
          <orderentryabo:CurrencyCode>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:CurrencyCode"/>
          </orderentryabo:CurrencyCode>
          <orderentryabo:DisconnectReason>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:DisconnectReason"/>
          </orderentryabo:DisconnectReason>
          <orderentryabo:OrderPriority>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:OrderPriority"/>
          </orderentryabo:OrderPriority>
          <orderentryabo:Status>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:Status"/>
          </orderentryabo:Status>
          <orderentryabo:OrderDate>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:OrderDate"/>
          </orderentryabo:OrderDate>
          <orderentryabo:OrderNumber>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:OrderNumber"/>
          </orderentryabo:OrderNumber>
          <orderentryabo:OrderType>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:OrderType"/>
          </orderentryabo:OrderType>
          <orderentryabo:Organization>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:Organization"/>
          </orderentryabo:Organization>
          <orderentryabo:ParentAccountId>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ParentAccountId"/>
          </orderentryabo:ParentAccountId>
          <orderentryabo:PrimaryAccountAddressGrade>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountAddressGrade"/>
          </orderentryabo:PrimaryAccountAddressGrade>
          <orderentryabo:PrimaryAccountAddressNumber>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountAddressNumber"/>
          </orderentryabo:PrimaryAccountAddressNumber>
          <orderentryabo:PrimaryAccountAreaCode>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountAreaCode"/>
          </orderentryabo:PrimaryAccountAreaCode>
          <orderentryabo:PrimaryAccountBetweenStreet1>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountBetweenStreet1"/>
          </orderentryabo:PrimaryAccountBetweenStreet1>
          <orderentryabo:PrimaryAccountBetweenStreet2>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountBetweenStreet2"/>
          </orderentryabo:PrimaryAccountBetweenStreet2>
          <orderentryabo:PrimaryAccountBillToCounty>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountBillToCounty"/>
          </orderentryabo:PrimaryAccountBillToCounty>
          <orderentryabo:PrimaryAccountBillToExternalNum>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountBillToExternalNum"/>
          </orderentryabo:PrimaryAccountBillToExternalNum>
          <orderentryabo:PrimaryAccountBillToInternalNum>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountBillToInternalNum"/>
          </orderentryabo:PrimaryAccountBillToInternalNum>
          <orderentryabo:PrimaryAccountBillToPostalCode>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountBillToPostalCode"/>
          </orderentryabo:PrimaryAccountBillToPostalCode>
          <orderentryabo:PrimaryAccountBillToState>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountBillToState"/>
          </orderentryabo:PrimaryAccountBillToState>
          <orderentryabo:PrimaryAccountBillToStreetAddress>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountBillToStreetAddress"/>
          </orderentryabo:PrimaryAccountBillToStreetAddress>
          <orderentryabo:PrimaryAccountBillToStreetAddress2>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountBillToStreetAddress2"/>
          </orderentryabo:PrimaryAccountBillToStreetAddress2>
          <orderentryabo:PrimaryAccountBillToStreetAddress3>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountBillToStreetAddress3"/>
          </orderentryabo:PrimaryAccountBillToStreetAddress3>
          <orderentryabo:PrimaryAccountCity>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountCity"/>
          </orderentryabo:PrimaryAccountCity>
          <orderentryabo:PrimaryAccountCountry>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountCountry"/>
          </orderentryabo:PrimaryAccountCountry>
          <orderentryabo:PrimaryAccountCounty>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountCounty"/>
          </orderentryabo:PrimaryAccountCounty>
          <orderentryabo:PrimaryAccountInternalNum>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountInternalNum"/>
          </orderentryabo:PrimaryAccountInternalNum>
          <orderentryabo:PrimaryAccountKeyAccess>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountKeyAccess"/>
          </orderentryabo:PrimaryAccountKeyAccess>
          <orderentryabo:PrimaryAccountLocalityCode>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountLocalityCode"/>
          </orderentryabo:PrimaryAccountLocalityCode>
          <orderentryabo:PrimaryAccountPhoneNum>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountPhoneNum"/>
          </orderentryabo:PrimaryAccountPhoneNum>
          <orderentryabo:PrimaryAccountPostalCode>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountPostalCode"/>
          </orderentryabo:PrimaryAccountPostalCode>
          <orderentryabo:PrimaryAccountState>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountState"/>
          </orderentryabo:PrimaryAccountState>
          <orderentryabo:PrimaryAccountStreetAddress>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountStreetAddress"/>
          </orderentryabo:PrimaryAccountStreetAddress>
          <orderentryabo:PrimaryAccountStreetAddress2>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountStreetAddress2"/>
          </orderentryabo:PrimaryAccountStreetAddress2>
          <orderentryabo:PrimaryAccountValidatedAddress>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountValidatedAddress"/>
          </orderentryabo:PrimaryAccountValidatedAddress>
          <orderentryabo:PrimaryBillToFirstName>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryBillToFirstName"/>
          </orderentryabo:PrimaryBillToFirstName>
          <orderentryabo:PrimaryBillToFiscalName>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryBillToFiscalName"/>
          </orderentryabo:PrimaryBillToFiscalName>
          <orderentryabo:PrimaryBillToLastName>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryBillToLastName"/>
          </orderentryabo:PrimaryBillToLastName>
          <orderentryabo:PrimaryBillToMailAddress>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryBillToMailAddress"/>
          </orderentryabo:PrimaryBillToMailAddress>
          <orderentryabo:PrimaryBillToMiddleName>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryBillToMiddleName"/>
          </orderentryabo:PrimaryBillToMiddleName>
          <orderentryabo:PrimaryBillToRFC>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryBillToRFC"/>
          </orderentryabo:PrimaryBillToRFC>
          <orderentryabo:PrimaryShipToAddressNumber>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryShipToAddressNumber"/>
          </orderentryabo:PrimaryShipToAddressNumber>
          <orderentryabo:PrimaryShipToCity>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryShipToCity"/>
          </orderentryabo:PrimaryShipToCity>
          <orderentryabo:PrimaryShipToCountry>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryShipToCountry"/>
          </orderentryabo:PrimaryShipToCountry>
          <orderentryabo:PrimaryShipToCounty>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryShipToCounty"/>
          </orderentryabo:PrimaryShipToCounty>
          <orderentryabo:PrimaryShipToInternalNum>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryShipToInternalNum"/>
          </orderentryabo:PrimaryShipToInternalNum>
          <orderentryabo:PrimaryShipToPostalCode>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryShipToPostalCode"/>
          </orderentryabo:PrimaryShipToPostalCode>
          <orderentryabo:PrimaryShipToProvince>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryShipToProvince"/>
          </orderentryabo:PrimaryShipToProvince>
          <orderentryabo:PrimaryShipToState>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryShipToState"/>
          </orderentryabo:PrimaryShipToState>
          <orderentryabo:PrimaryShipToStreetAddress>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryShipToStreetAddress"/>
          </orderentryabo:PrimaryShipToStreetAddress>
          <orderentryabo:RequestedShipDate>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:RequestedShipDate"/>
          </orderentryabo:RequestedShipDate>
          <orderentryabo:SAPId>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:SAPId"/>
          </orderentryabo:SAPId>
          <orderentryabo:SOAServiceName>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:SOAServiceName"/>
          </orderentryabo:SOAServiceName>
          <orderentryabo:ServiceAccountBillType>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ServiceAccountBillType"/>
          </orderentryabo:ServiceAccountBillType>
          <orderentryabo:ServiceAccountEmployeeNumber>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ServiceAccountEmployeeNumber"/>
          </orderentryabo:ServiceAccountEmployeeNumber>
          <orderentryabo:ServiceAccountMasterId>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ServiceAccountMasterId"/>
          </orderentryabo:ServiceAccountMasterId>
          <orderentryabo:ServiceAccountType>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ServiceAccountType"/>
          </orderentryabo:ServiceAccountType>
          <orderentryabo:ServiceOrderId>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ServiceOrderId"/>
          </orderentryabo:ServiceOrderId>
          <orderentryabo:Source>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:Source"/>
          </orderentryabo:Source>
          <orderentryabo:SubOrderType>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:SubOrderType"/>
          </orderentryabo:SubOrderType>
          <orderentryabo:InternetServicesFlag>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:InternetServicesFlag"/>
          </orderentryabo:InternetServicesFlag>
          <orderentryabo:AccAssocStatus>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccAssocStatus"/>
          </orderentryabo:AccAssocStatus>
          <orderentryabo:AlertNumber>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AlertNumber"/>
          </orderentryabo:AlertNumber>
          <orderentryabo:POIDAction>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:POIDAction"/>
          </orderentryabo:POIDAction>          
          <orderentryabo:DistributorThatActivates>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:DistributorThatActivates"/>
          </orderentryabo:DistributorThatActivates>
          <orderentryabo:CorrelationId>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:CorrelationId"/>
          </orderentryabo:CorrelationId>
          <orderentryabo:PromoCode>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PromoCode"/>
          </orderentryabo:PromoCode>
          <orderentryabo:PrimaryAccountProvince>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryAccountProvince"/>
          </orderentryabo:PrimaryAccountProvince>
          <orderentryabo:PreActivateFlag>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PreActivateFlag"/>
          </orderentryabo:PreActivateFlag>
          <orderentryabo:BillingProfilePaymentSystem>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:BillingProfilePaymentSystem"/>
          </orderentryabo:BillingProfilePaymentSystem>
          <orderentryabo:ChangeBillingProfilePaymentSystem>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ChangeBillingProfilePaymentSystem"/>
          </orderentryabo:ChangeBillingProfilePaymentSystem>
          <orderentryabo:AgreementSubscriptionAmount>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AgreementSubscriptionAmount"/>
          </orderentryabo:AgreementSubscriptionAmount>
          <orderentryabo:MultiPaquete>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:MultiPaquete"/>
          </orderentryabo:MultiPaquete>
           <!--Apertura. Atributos nuevos agregados a la orden. Nuevo modelo de tipo de cuenta-->
          <orderentryabo:AccountTypeRecharge>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountTypeRecharge"/>
          </orderentryabo:AccountTypeRecharge>
          <orderentryabo:AccountServicesUser>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountServicesUser"/>
          </orderentryabo:AccountServicesUser>
          <orderentryabo:AccountServicesSystem>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountServicesSystem"/>
          </orderentryabo:AccountServicesSystem>
          <orderentryabo:ComInvoiceBillPaymentSystem>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ComInvoiceBillPaymentSystem"/>
          </orderentryabo:ComInvoiceBillPaymentSystem>
          
          <orderentryabo:AccountTypeService>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountTypeService"/>
          </orderentryabo:AccountTypeService>
          <orderentryabo:AccountService>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountService"/>
          </orderentryabo:AccountService>
          <orderentryabo:AccountServiceWeighting>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountServiceWeighting"/>
          </orderentryabo:AccountServiceWeighting>
          <orderentryabo:AccountServiceType>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountServiceType"/>
          </orderentryabo:AccountServiceType>
          <orderentryabo:AccountServiceTypeWeighting>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountServiceTypeWeighting"/>
          </orderentryabo:AccountServiceTypeWeighting>
          <orderentryabo:AccountDeviceNumbersWeighting>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountDeviceNumbersWeighting"/>
          </orderentryabo:AccountDeviceNumbersWeighting>
          <orderentryabo:ServicesPackage>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ServicesPackage"/>
          </orderentryabo:ServicesPackage>
          <orderentryabo:AccountServiceTypeWeightingDetail>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:AccountServiceTypeWeightingDetail"/>
          </orderentryabo:AccountServiceTypeWeightingDetail>
          <!--Cierre. Atributos nuevos agregados a la orden. Nuevo modelo de tipo de cuenta.-->
          <orderentryabo:VideoMasterBouquetId>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:VideoMasterBouquetId"/>
          </orderentryabo:VideoMasterBouquetId>
          <orderentryabo:EquipmentsVideo>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:EquipmentsVideo"/>
          </orderentryabo:EquipmentsVideo>
          <orderentryabo:EquipmentsBroadband>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:EquipmentsBroadband"/>
          </orderentryabo:EquipmentsBroadband>
          <orderentryabo:LoginEmailAddress>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:LoginEmailAddress"/>
          </orderentryabo:LoginEmailAddress>          
           <orderentryabo:OTTUser>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:OTTUser"/>
          </orderentryabo:OTTUser>
           <orderentryabo:OTTPassword>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:OTTPassword"/>
          </orderentryabo:OTTPassword>
           <orderentryabo:CountryCode>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:CountryCode"/>
          </orderentryabo:CountryCode>          
           <orderentryabo:PrimaryBillToTaxRegime>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryBillToTaxRegime"/>
          </orderentryabo:PrimaryBillToTaxRegime>
           <orderentryabo:PrimaryBillToUseCFDI>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:PrimaryBillToUseCFDI"/>
          </orderentryabo:PrimaryBillToUseCFDI>          
           <orderentryabo:BillingProfilePaymentInstrument>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:BillingProfilePaymentInstrument"/>
          </orderentryabo:BillingProfilePaymentInstrument>
           <orderentryabo:BillingProfileInstrumentIdentifier>
            <xsl:value-of select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:BillingProfileInstrumentIdentifier"/>
          </orderentryabo:BillingProfileInstrumentIdentifier>
          
          <orderentryabo:ListOfComWorkOrder-ServiceInstances>
          <xsl:for-each select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ListOfComWorkOrder-ServiceInstances/orderentryabo:ComWorkOrder-ServiceInstances[not(orderentryabo:ServiceInstance = preceding-sibling::orderentryabo:ComWorkOrder-ServiceInstances/orderentryabo:ServiceInstance)]">
                <xsl:sort selec="orderentryabo:ServiceInstance" order="ascending"/>
                <orderentryabo:ComWorkOrder-ServiceInstances>
                     <orderentryabo:ServiceInstance>
                        <xsl:value-of select="orderentryabo:ServiceInstance"/>
                     </orderentryabo:ServiceInstance>
					<orderentryabo:ServiceActionCode>
						<xsl:value-of select="orderentryabo:ServiceActionCode"/>
					</orderentryabo:ServiceActionCode>
                </orderentryabo:ComWorkOrder-ServiceInstances>
          </xsl:for-each>
          </orderentryabo:ListOfComWorkOrder-ServiceInstances>
          <orderentryabo:ListOfComWorkOrder-ReplaceItems>
          <xsl:for-each select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ListOfComWorkOrder-ReplaceItems/orderentryabo:ComWorkOrder-ReplaceItems[not(orderentryabo:ParentEquipmentId = preceding-sibling::orderentryabo:ComWorkOrder-ReplaceItems/orderentryabo:ParentEquipmentId)]">
              <orderentryabo:ComWorkOrder-ReplaceItems>
                 <orderentryabo:ParentEquipmentId>
                    <xsl:value-of select="orderentryabo:ParentEquipmentId"/>
                  </orderentryabo:ParentEquipmentId>
                  <orderentryabo:PositionReplace>
                    <xsl:value-of select="position()"/>
                  </orderentryabo:PositionReplace>
              </orderentryabo:ComWorkOrder-ReplaceItems>
            </xsl:for-each>
         </orderentryabo:ListOfComWorkOrder-ReplaceItems>
          <!-- Apr2017 AJNR Primero se identifican los paquetes root que se van a agregar, luego los que se eliminaran y solo si no existen ninguno de los dos; solo se colocan los paquetes root. -->
          <xsl:variable name="packagesAdd"
                        select="count(/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ListOfComWorkOrder-LineItems/orderentryabo:ComWorkOrder-LineItems[(orderentryabo:ProductTypeIntegration='Package' or orderentryabo:ProductTypeCodeCRM='Paquete' or orderentryabo:ProductTypeCodeCRM='Paquete Principal') and orderentryabo:ActionCode = 'New' and orderentryabo:ProductTypeCode = 'Producto'])"/>
          <xsl:variable name="packagesDelete"
                        select="count(/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ListOfComWorkOrder-LineItems/orderentryabo:ComWorkOrder-LineItems[(orderentryabo:ProductTypeIntegration='Package' or orderentryabo:ProductTypeCodeCRM='Paquete' or orderentryabo:ProductTypeCodeCRM='Paquete Principal') and orderentryabo:ActionCode = 'Deleted' and orderentryabo:ProductTypeCode = 'Producto'])"/>
          <orderentryabo:ListOfComWorkOrder-RootItems>
            <xsl:if test="$packagesAdd > 0">
              <xsl:for-each select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ListOfComWorkOrder-LineItems/orderentryabo:ComWorkOrder-LineItems[(orderentryabo:ProductTypeIntegration='Package' or orderentryabo:ProductTypeCodeCRM='Paquete' or orderentryabo:ProductTypeCodeCRM='Paquete Principal') and orderentryabo:ProductTypeCode = 'Producto' and orderentryabo:ActionCode = 'New']">
                <xsl:if test="position() = 1">
                  <orderentryabo:ComWorkOrder-RootItems>
                    <orderentryabo:Id>
                      <xsl:value-of select="orderentryabo:Id"/>
                    </orderentryabo:Id>
                    <orderentryabo:InfId>
                      <xsl:value-of select="orderentryabo:InfId"/>
                    </orderentryabo:InfId>
                    <orderentryabo:ActionCode>
                      <xsl:value-of select="orderentryabo:ActionCode"/>
                    </orderentryabo:ActionCode>
                    <orderentryabo:Key>
                      <xsl:value-of select="orderentryabo:Key"/>
                    </orderentryabo:Key>
                    <orderentryabo:PartNumber>
                      <xsl:value-of select="orderentryabo:PartNumber"/>
                    </orderentryabo:PartNumber>
                    <orderentryabo:PaymentScheme>
                      <xsl:value-of select="dvm:lookupValue('oramds:/apps/AIAMetaData/dvm/SALESORDER_CONFIG_CROSSREFERENCE.dvm','SOA_01', xp20:upper-case(oraext:query-database(concat(&quot;select /*+ FIRST_ROWS(1)*/ SUBTIPO from ofertacomercial_codes where nombre_producto='&quot;,orderentryabo:Product,&quot;' and siebel_id='&quot;,orderentryabo:PartNumber,&quot;' and rownum=1 &quot;),false(),false(),&quot;jdbc/usr_ofcomer&quot;)),'SOA_03','CouldNotBeFound')"/>
                    </orderentryabo:PaymentScheme>
                  </orderentryabo:ComWorkOrder-RootItems>
                </xsl:if>    
              </xsl:for-each>
            </xsl:if>
            <xsl:if test="$packagesDelete > 0">
              <xsl:for-each select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ListOfComWorkOrder-LineItems/orderentryabo:ComWorkOrder-LineItems[(orderentryabo:ProductTypeIntegration='Package' or orderentryabo:ProductTypeCodeCRM='Paquete' or orderentryabo:ProductTypeCodeCRM='Paquete Principal') and orderentryabo:ProductTypeCode = 'Producto' and orderentryabo:ActionCode = 'Deleted']">
                <xsl:if test="position() = 1">
                  <orderentryabo:ComWorkOrder-RootItems>
                    <orderentryabo:Id>
                      <xsl:value-of select="orderentryabo:Id"/>
                    </orderentryabo:Id>
                    <orderentryabo:InfId>
                      <xsl:value-of select="orderentryabo:InfId"/>
                    </orderentryabo:InfId>
                    <orderentryabo:ActionCode>
                      <xsl:value-of select="orderentryabo:ActionCode"/>
                    </orderentryabo:ActionCode>
                    <orderentryabo:Key>
                      <xsl:value-of select="orderentryabo:Key"/>
                    </orderentryabo:Key>
                    <orderentryabo:PartNumber>
                      <xsl:value-of select="orderentryabo:PartNumber"/>
                    </orderentryabo:PartNumber>
                    <orderentryabo:PaymentScheme>
                      <xsl:value-of select="dvm:lookupValue('oramds:/apps/AIAMetaData/dvm/SALESORDER_CONFIG_CROSSREFERENCE.dvm','SOA_01', xp20:upper-case(oraext:query-database(concat(&quot;select /*+ FIRST_ROWS(1)*/ SUBTIPO from ofertacomercial_codes where nombre_producto='&quot;,orderentryabo:Product,&quot;' and siebel_id='&quot;,orderentryabo:PartNumber,&quot;' and rownum=1 &quot;),false(),false(),&quot;jdbc/usr_ofcomer&quot;)),'SOA_03','CouldNotBeFound')"/>
                    </orderentryabo:PaymentScheme>
                  </orderentryabo:ComWorkOrder-RootItems>
                </xsl:if>    
              </xsl:for-each>            
            </xsl:if>
          </orderentryabo:ListOfComWorkOrder-RootItems>
          <orderentryabo:ListOfComWorkOrder-LineItems>
            <xsl:for-each select="/orderentryabo:SiebelMessage/orderentryabo:ListOfSkyhjComWorkOrder/orderentryabo:ComWorkOrder-Orders/orderentryabo:ListOfComWorkOrder-LineItems/orderentryabo:ComWorkOrder-LineItems">
              <xsl:variable name="productType" 
                select="oraext:query-database(concat(&quot;select /*+ FIRST_ROWS(1)*/ OSM_ID from ofertacomercial_codes where nombre_producto='&quot;,orderentryabo:Product,&quot;' and siebel_id='&quot;,orderentryabo:PartNumber,&quot;' and rownum=1 &quot;),false(),false(),&quot;jdbc/usr_ofcomer&quot;)"/>
              <xsl:if test="xp20:upper-case($productType) != 'DUMMY'">
                  <orderentryabo:ComWorkOrder-LineItems>
                    <orderentryabo:Id>
                      <xsl:value-of select="orderentryabo:Id"/>
                    </orderentryabo:Id>
                    <orderentryabo:InfId>
                      <xsl:value-of select="orderentryabo:InfId"/>
                    </orderentryabo:InfId>
                    <orderentryabo:ActionCode>
                      <xsl:value-of select="orderentryabo:ActionCode"/>
                    </orderentryabo:ActionCode>
                    <orderentryabo:AssetId>
                      <xsl:value-of select="orderentryabo:AssetId"/>
                    </orderentryabo:AssetId>
                    <orderentryabo:AssetInternet>
                      <xsl:value-of select="orderentryabo:AssetInternet"/>
                    </orderentryabo:AssetInternet>
                    <orderentryabo:AssetInternetEquipmentMAC>
                      <xsl:value-of select="orderentryabo:AssetInternetEquipmentMAC"/>
                    </orderentryabo:AssetInternetEquipmentMAC>
                    <orderentryabo:AssetInternetEquipmentManufacturer>
                      <xsl:value-of select="orderentryabo:AssetInternetEquipmentManufacturer"/>
                    </orderentryabo:AssetInternetEquipmentManufacturer>
                    <orderentryabo:AssetInternetEquipmentModel>
                      <xsl:value-of select="orderentryabo:AssetInternetEquipmentModel"/>
                    </orderentryabo:AssetInternetEquipmentModel>
                    <orderentryabo:AssetInternetEquipmentType>
                      <xsl:value-of select="orderentryabo:AssetInternetEquipmentType"/>
                    </orderentryabo:AssetInternetEquipmentType>
                    <orderentryabo:AssetInternetPackageSpeed>
                      <xsl:value-of select="orderentryabo:AssetInternetPackageSpeed"/>
                    </orderentryabo:AssetInternetPackageSpeed>
                    <orderentryabo:AssetInternetTransactionId>
                      <xsl:value-of select="orderentryabo:AssetInternetTransactionId"/>
                    </orderentryabo:AssetInternetTransactionId>
                    <orderentryabo:AssetNumber>
                      <xsl:value-of select="orderentryabo:AssetNumber"/>
                    </orderentryabo:AssetNumber>
                    <orderentryabo:AssetReceiverId>
                      <xsl:value-of select="orderentryabo:AssetReceiverId"/>
                    </orderentryabo:AssetReceiverId>
                    <orderentryabo:AssetServiceProduct>
                      <xsl:value-of select="orderentryabo:AssetServiceProduct"/>
                    </orderentryabo:AssetServiceProduct>
                    <orderentryabo:AssetSupportedTechnology>
                      <xsl:value-of select="orderentryabo:AssetSupportedTechnology"/>
                    </orderentryabo:AssetSupportedTechnology>
                    <orderentryabo:Bouquet>
                      <xsl:value-of select="orderentryabo:Bouquet"/>
                    </orderentryabo:Bouquet>
                    <orderentryabo:CallbackDay>
                      <xsl:value-of select="orderentryabo:CallbackDay"/>
                    </orderentryabo:CallbackDay>
                    <orderentryabo:DistributorThatActivates>
                      <xsl:value-of select="orderentryabo:DistributorThatActivates"/>
                    </orderentryabo:DistributorThatActivates>
                    <orderentryabo:EffectiveStartDate>
                      <xsl:value-of select="orderentryabo:EffectiveStartDate"/>
                    </orderentryabo:EffectiveStartDate>
                    <orderentryabo:EffectiveEndDate>
                      <xsl:value-of select="orderentryabo:EffectiveEndDate"/>
                    </orderentryabo:EffectiveEndDate>
                    <orderentryabo:Hierarchy>
                      <xsl:value-of select="orderentryabo:Hierarchy"/>
                    </orderentryabo:Hierarchy>
                    <orderentryabo:IntegrationId>
                      <xsl:value-of select="orderentryabo:IntegrationId"/>
                    </orderentryabo:IntegrationId>
                    <orderentryabo:LineNumber>
                      <xsl:value-of select="orderentryabo:LineNumber"/>
                    </orderentryabo:LineNumber>
                    <orderentryabo:OrderHeaderId>
                      <xsl:value-of select="orderentryabo:OrderHeaderId"/>
                    </orderentryabo:OrderHeaderId>
                    <orderentryabo:PPEContent>
                      <xsl:value-of select="orderentryabo:PPEContent"/>
                    </orderentryabo:PPEContent>
                    <orderentryabo:PPEEventTitle>
                      <xsl:value-of select="orderentryabo:PPEEventTitle"/>
                    </orderentryabo:PPEEventTitle>
                    <orderentryabo:PPEEventType>
                      <xsl:value-of select="orderentryabo:PPEEventType"/>
                    </orderentryabo:PPEEventType>
                    <orderentryabo:PPETrackingId>
                      <xsl:value-of select="orderentryabo:PPETrackingId"/>
                    </orderentryabo:PPETrackingId>
                    <orderentryabo:PPEChannel>
                      <xsl:value-of select="orderentryabo:PPEChannel"/>
                    </orderentryabo:PPEChannel>
                    <orderentryabo:PPETokenId>
                      <xsl:value-of select="orderentryabo:PPETokenId"/>
                    </orderentryabo:PPETokenId>
                    <orderentryabo:ParentOrderItemId>
                      <xsl:value-of select="orderentryabo:ParentOrderItemId"/>
                    </orderentryabo:ParentOrderItemId>
                    <orderentryabo:PartNumber>
                      <xsl:value-of select="orderentryabo:PartNumber"/>
                    </orderentryabo:PartNumber>
                    <orderentryabo:Product>
                      <xsl:value-of select="orderentryabo:Product"/>
                    </orderentryabo:Product>
                    <orderentryabo:ProductId>
                      <xsl:value-of select="orderentryabo:ProductId"/>
                    </orderentryabo:ProductId>
                    <orderentryabo:AssetModel>
                        <xsl:value-of select="orderentryabo:AssetModel"/>
                    </orderentryabo:AssetModel>
                    <orderentryabo:AssetTypeCode>
                      <xsl:value-of select="orderentryabo:AssetTypeCode"/>
                    </orderentryabo:AssetTypeCode>
                    <orderentryabo:ProductTypeCode>
                      <xsl:value-of select="orderentryabo:ProductTypeCode"/>
                    </orderentryabo:ProductTypeCode>
                    <orderentryabo:ProductTypeCodeCRM>
                        <xsl:value-of select="orderentryabo:ProductTypeCodeCRM"/>
                    </orderentryabo:ProductTypeCodeCRM>
                    <orderentryabo:ProductTypeIntegration>
                      <xsl:value-of select="orderentryabo:ProductTypeIntegration"/>
                    </orderentryabo:ProductTypeIntegration>
                    <orderentryabo:ProductSubTypeIntegration>
                      <xsl:value-of select="orderentryabo:ProductSubTypeIntegration"/>
                    </orderentryabo:ProductSubTypeIntegration>
                    <orderentryabo:Quantity>
                      <xsl:value-of select="orderentryabo:Quantity"/>
                    </orderentryabo:Quantity>
                    <orderentryabo:ReplacementReason>
                      <xsl:value-of select="orderentryabo:ReplacementReason"/>
                    </orderentryabo:ReplacementReason>
                    <orderentryabo:RootOrderItemId>
                      <xsl:value-of select="orderentryabo:RootOrderItemId"/>
                    </orderentryabo:RootOrderItemId>
                    <orderentryabo:Status>
                      <xsl:value-of select="orderentryabo:Status"/>
                    </orderentryabo:Status>
                    <orderentryabo:StatusIPPV>
                      <xsl:value-of select="orderentryabo:StatusIPPV"/>
                    </orderentryabo:StatusIPPV>
                    <orderentryabo:Supplier>
                      <xsl:value-of select="orderentryabo:Supplier"/>
                    </orderentryabo:Supplier>
                    <orderentryabo:RemBookManufacturerCode>
                      <xsl:value-of select="orderentryabo:RemBookManufacturerCode"/>
                    </orderentryabo:RemBookManufacturerCode>
                    <orderentryabo:RemBookSeason>
                      <xsl:value-of select="orderentryabo:RemBookSeason"/>
                    </orderentryabo:RemBookSeason>
                    <orderentryabo:RemBookRecurringFlag>
                      <xsl:value-of select="orderentryabo:RemBookRecurringFlag"/>
                    </orderentryabo:RemBookRecurringFlag>
                    <orderentryabo:RemBookMethodType>
                      <xsl:value-of select="orderentryabo:RemBookMethodType"/>
                    </orderentryabo:RemBookMethodType>
                    <orderentryabo:RemBookChannel>
                      <xsl:value-of select="orderentryabo:RemBookChannel"/>
                    </orderentryabo:RemBookChannel>
                    <orderentryabo:RemBookSeriesId>
                      <xsl:value-of select="orderentryabo:RemBookSeriesId"/>
                    </orderentryabo:RemBookSeriesId>
                    <orderentryabo:RemBookDuration>
                      <xsl:value-of select="orderentryabo:RemBookDuration"/>
                    </orderentryabo:RemBookDuration>
                    <orderentryabo:RemBookSequenceNumber>
                      <xsl:value-of select="orderentryabo:RemBookSequenceNumber"/>
                    </orderentryabo:RemBookSequenceNumber>
                    <orderentryabo:RemBookEpisodeId>
                      <xsl:value-of select="orderentryabo:RemBookEpisodeId"/>
                    </orderentryabo:RemBookEpisodeId>
                    <orderentryabo:RemBookRecordingConfiguration>
                      <xsl:value-of select="orderentryabo:RemBookRecordingConfiguration"/>
                    </orderentryabo:RemBookRecordingConfiguration>
                    <orderentryabo:RemBookExpirationTime>
                      <xsl:value-of select="orderentryabo:RemBookExpirationTime"/>
                    </orderentryabo:RemBookExpirationTime>
                    <orderentryabo:RemBookContentType>
                      <xsl:value-of select="orderentryabo:RemBookContentType"/>
                    </orderentryabo:RemBookContentType>
                    <orderentryabo:RemBookRecordingType>
                      <xsl:value-of select="orderentryabo:RemBookRecordingType"/>
                    </orderentryabo:RemBookRecordingType>
                    <orderentryabo:RemBookStartTime>
                      <xsl:value-of select="orderentryabo:RemBookStartTime"/>
                    </orderentryabo:RemBookStartTime>
                    
                     <orderentryabo:RemBookComercialNumber>
                      <xsl:value-of select="orderentryabo:RemBookComercialNumber"/>
                    </orderentryabo:RemBookComercialNumber>
                     <orderentryabo:RemBookIdUniqueChannel>
                      <xsl:value-of select="orderentryabo:RemBookIdUniqueChannel"/>
                    </orderentryabo:RemBookIdUniqueChannel>
                    <orderentryabo:RemBookEventName>
                      <xsl:value-of select="orderentryabo:RemBookEventName"/>
                    </orderentryabo:RemBookEventName>
                     <orderentryabo:RemBookEventId>
                      <xsl:value-of select="orderentryabo:RemBookEventId"/>
                    </orderentryabo:RemBookEventId>
                    <orderentryabo:RemBookContentId>
                      <xsl:value-of select="orderentryabo:RemBookContentId"/>
                    </orderentryabo:RemBookContentId>
                     <orderentryabo:RemBookContentProvider>
                      <xsl:value-of select="orderentryabo:RemBookContentProvider"/>
                    </orderentryabo:RemBookContentProvider>
                    <orderentryabo:RemBookOriginalNetwork>
                      <xsl:value-of select="orderentryabo:RemBookOriginalNetwork"/>
                    </orderentryabo:RemBookOriginalNetwork>
                     <orderentryabo:RemBookTransportStream>
                      <xsl:value-of select="orderentryabo:RemBookTransportStream"/>
                    </orderentryabo:RemBookTransportStream>
                    <orderentryabo:RemBookProgramId>
                      <xsl:value-of select="orderentryabo:RemBookProgramId"/>
                    </orderentryabo:RemBookProgramId>
                     <orderentryabo:RemBookRecurrence>
                      <xsl:value-of select="orderentryabo:RemBookRecurrence"/>
                    </orderentryabo:RemBookRecurrence>
                    <orderentryabo:RemBookReminder>
                      <xsl:value-of select="orderentryabo:RemBookReminder"/>
                    </orderentryabo:RemBookReminder>
                     <orderentryabo:Source>
                      <xsl:value-of select="orderentryabo:Source"/>
                    </orderentryabo:Source>    
                    <orderentryabo:PreviousMasterSmartcard>
                      <xsl:value-of select="orderentryabo:PreviousMasterSmartcard"/>
                    </orderentryabo:PreviousMasterSmartcard>
                    <orderentryabo:ActivationCode>
                      <xsl:value-of select="orderentryabo:ActivationCode"/>
                    </orderentryabo:ActivationCode>
                    <orderentryabo:AssetTypeIRD>
                      <xsl:value-of select="orderentryabo:AssetTypeIRD"/>
                    </orderentryabo:AssetTypeIRD>
                    <xsl:choose>
                      <xsl:when test="orderentryabo:ProductTypeCode = 'Producto'">
                        <orderentryabo:Key>
                          <xsl:value-of select="dvm:lookupValue('oramds:/apps/AIAMetaData/dvm/SALESORDER_PRODUCTTYPECODE.dvm','COMMON',$productType,'SOA_PRIORITY_CODE','0','SOA_SERVICIO','-')"/>
                        </orderentryabo:Key>
                      </xsl:when>
                      <xsl:when test="orderentryabo:ProductTypeCode != 'Producto' and orderentryabo:AssetTypeCode='IRD'">
                        <orderentryabo:Key>
                          <xsl:value-of select="dvm:lookupValue('oramds:/apps/AIAMetaData/dvm/SALESORDER_PRODUCTTYPECODE.dvm','COMMON','Equipment','SOA_PRIORITY_CODE','0','SOA_SERVICIO','-')"/>
                        </orderentryabo:Key>
                      </xsl:when>
                    </xsl:choose>
                    <orderentryabo:UploadSpeed>
                        <xsl:value-of select="orderentryabo:UploadSpeed"/>
                    </orderentryabo:UploadSpeed>
                    <orderentryabo:DownloadSpeed>
                        <xsl:value-of select="orderentryabo:DownloadSpeed"/>
                    </orderentryabo:DownloadSpeed>
                    <orderentryabo:EquipoMigradoFlag>
                        <xsl:value-of select="orderentryabo:EquipoMigradoFlag"/>
                    </orderentryabo:EquipoMigradoFlag>
                    <orderentryabo:PrimaryAddressId>
                        <xsl:value-of select="orderentryabo:PrimaryAddressId"/>
                    </orderentryabo:PrimaryAddressId>
                    <orderentryabo:SalesChannel>
                        <xsl:value-of select="orderentryabo:SalesChannel"/>
                    </orderentryabo:SalesChannel>
                    <orderentryabo:ParentServiceInstanceId>
                        <xsl:value-of select="orderentryabo:ParentServiceInstanceId"/>
                    </orderentryabo:ParentServiceInstanceId>
                    <orderentryabo:ServiceAccountAddressLongitude>
                        <xsl:value-of select="orderentryabo:ServiceAccountAddressLongitude"/>
                    </orderentryabo:ServiceAccountAddressLongitude>
                    <orderentryabo:ServiceAccountAddressLatitude>
                        <xsl:value-of select="orderentryabo:ServiceAccountAddressLatitude"/>
                    </orderentryabo:ServiceAccountAddressLatitude>
                    <orderentryabo:IMSI>
                        <xsl:value-of select="orderentryabo:IMSI"/>
                    </orderentryabo:IMSI>
                    <orderentryabo:MSISDN>
                        <xsl:value-of select="orderentryabo:MSISDN"/>
                    </orderentryabo:MSISDN>
                    <orderentryabo:Technology>
                        <xsl:value-of select="orderentryabo:Technology"/>
                    </orderentryabo:Technology>
                    <orderentryabo:UnitMeasure>
                        <xsl:value-of select="orderentryabo:UnitMeasure"/>
                    </orderentryabo:UnitMeasure>
                    <orderentryabo:UOMUploadSpeed>
                        <xsl:value-of select="orderentryabo:UOMUploadSpeed"/>
                    </orderentryabo:UOMUploadSpeed>
                    <orderentryabo:UOMDownloadSpeed>
                        <xsl:value-of select="orderentryabo:UOMDownloadSpeed"/>
                    </orderentryabo:UOMDownloadSpeed>
                    <orderentryabo:ServiceProductType>
                        <xsl:value-of select="orderentryabo:ServiceProductType"/>
                    </orderentryabo:ServiceProductType>
                    <orderentryabo:Promotion>
                        <xsl:value-of select="orderentryabo:Promotion"/>
                    </orderentryabo:Promotion>
                    <orderentryabo:AgreementSubscriptionAmount>
                        <xsl:value-of select="orderentryabo:AgreementSubscriptionAmount"/>
                    </orderentryabo:AgreementSubscriptionAmount>
                    <orderentryabo:AgreementNameLine>
                        <xsl:value-of select="orderentryabo:AgreementNameLine"/>
                    </orderentryabo:AgreementNameLine>
                    <orderentryabo:FlagTermsConditions>
                        <xsl:value-of select="orderentryabo:FlagTermsConditions"/>
                    </orderentryabo:FlagTermsConditions>
                    <orderentryabo:EventTypeExtern>
                        <xsl:value-of select="orderentryabo:EventTypeExtern"/>
                    </orderentryabo:EventTypeExtern>
                    <orderentryabo:DataBag>
                        <xsl:value-of select="orderentryabo:DataBag"/>
                    </orderentryabo:DataBag>
                    <orderentryabo:ExternalOffer>
                        <xsl:value-of select="orderentryabo:ExternalOffer"/>
                    </orderentryabo:ExternalOffer>
                    <orderentryabo:UOMDataBag>
                        <xsl:value-of select="orderentryabo:UOMDataBag"/>
                    </orderentryabo:UOMDataBag>                    
                    <orderentryabo:CompanionDevices>
                    <xsl:value-of select="orderentryabo:CompanionDevices"/>
                  </orderentryabo:CompanionDevices>
                  <orderentryabo:HouseHoldId>
                    <xsl:value-of select="orderentryabo:HouseHoldId"/>
                  </orderentryabo:HouseHoldId>
                  <orderentryabo:AgreementSKYPromotion>
                    <xsl:value-of select="orderentryabo:AgreementSKYPromotion"/>
                  </orderentryabo:AgreementSKYPromotion>                   
                  <orderentryabo:MSISDNPorted>
                    <xsl:value-of select="orderentryabo:MSISDNPorted"/>
                  </orderentryabo:MSISDNPorted>
                  <orderentryabo:SMSPack>
                    <xsl:value-of select="orderentryabo:SMSPack"/>
                  </orderentryabo:SMSPack>
                  <orderentryabo:TimePack>
                    <xsl:value-of select="orderentryabo:TimePack"/>
                  </orderentryabo:TimePack>
                  <orderentryabo:UOMTimePack>
                    <xsl:value-of select="orderentryabo:UOMTimePack"/>
                  </orderentryabo:UOMTimePack>
                  <orderentryabo:ProductType>
                    <xsl:value-of select="orderentryabo:ProductType"/>
                  </orderentryabo:ProductType>
                  <orderentryabo:IntegratedDataBag>
                    <xsl:value-of select="orderentryabo:IntegratedDataBag"/>
                  </orderentryabo:IntegratedDataBag>
                  <orderentryabo:IntegratedUOMDataBag>
                    <xsl:value-of select="orderentryabo:IntegratedUOMDataBag"/>
                  </orderentryabo:IntegratedUOMDataBag>
                  <orderentryabo:IntegratedUploadSpeed>
                    <xsl:value-of select="orderentryabo:IntegratedUploadSpeed"/>
                  </orderentryabo:IntegratedUploadSpeed>
                  <orderentryabo:IntegratedUOMUploadSpeed>
                    <xsl:value-of select="orderentryabo:IntegratedUOMUploadSpeed"/>
                  </orderentryabo:IntegratedUOMUploadSpeed>
                  <orderentryabo:IntegratedDownloadSpeed>
                    <xsl:value-of select="orderentryabo:IntegratedDownloadSpeed"/>
                  </orderentryabo:IntegratedDownloadSpeed>
                  <orderentryabo:IntegratedUOMDownloadSpeed>
                    <xsl:value-of select="orderentryabo:IntegratedUOMDownloadSpeed"/>
                  </orderentryabo:IntegratedUOMDownloadSpeed>
                  <orderentryabo:GenerationTechnology>
                    <xsl:value-of select="orderentryabo:GenerationTechnology"/>
                  </orderentryabo:GenerationTechnology>
                  <orderentryabo:OriginalProductType>
                    <xsl:value-of select="orderentryabo:OriginalProductType"/>
                  </orderentryabo:OriginalProductType>
                  <orderentryabo:RegionCode>
                    <xsl:value-of select="orderentryabo:RegionCode"/>
                  </orderentryabo:RegionCode>    
                  <orderentryabo:CallForwardingNumber>
                    <xsl:value-of select="orderentryabo:CallForwardingNumber"/>
                  </orderentryabo:CallForwardingNumber>
                  <orderentryabo:TetheringServices>
                    <xsl:value-of select="orderentryabo:TetheringServices"/>
                  </orderentryabo:TetheringServices>
                  
                  </orderentryabo:ComWorkOrder-LineItems>
              </xsl:if>
            </xsl:for-each>
          </orderentryabo:ListOfComWorkOrder-LineItems>
        </orderentryabo:ComWorkOrder-Orders>
      </orderentryabo:ListOfSkyhjComWorkOrder>
    </orderentryabo:SiebelMessage>
  </xsl:template>
</xsl:stylesheet>